[tool.poetry]
name = "poc-neo4j"
version = "0.1.0"
description = ""
authors = ["uedaeita <eitaro.ueda@gmail.com>"]
packages = [
  { include="app", from="." },
  { include="tests", from="." },
]

[tool.poetry.scripts]
"provision:graph" = "app.service.provision.graph:main"

[tool.poetry.dependencies]
python = "^3.9"
alembic = "^1.7.7"
boto3 = "^1.21.30"
fastapi = "^0.75.0"
fastapi-camelcase = "^1.0.5"
pandas = "^1.4.1"
py2neo = "^2021.2.3"
pydantic = "^1.9.0"
PyMySQL = "^1.0.2"
python-cypher = "^0.20.0"
python-dotenv = "^0.19.2"
SQLAlchemy = "^1.4.32"
uvicorn = {extras = ["standard"], version = "^0.17.6"}

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
pysen = {version = "^0.10.1", extras = ["lint"]}
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pysen]
version = "0.10"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
line_length = 88
py_version = "py38"
[[tool.pysen.lint.mypy_targets]]
  paths = ["."]

[tool.pysen-cli]
settings_dir = "."

[tool.black] # automatically generated by pysen
line-length = 88
target-version = ["py38"]

[tool.isort] # automatically generated by pysen
default_section = "THIRDPARTY"
ensure_newline_before_comments = true
force_grid_wrap = 0
force_single_line = false
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true
